In [2]:
import pandas as pd

# Read in the data
df_dataset = pd.read_csv('dataset.tsv', sep='\t')

df_dataset

,GEO Series,Species,Samples,Title,Summary,Keyword,Publication,Journal,Institution,Country
0,GSE27323,Thermothelomyces thermophilus,7,Transcriptomic response to substrate and tempe...,The thermophilic filamentous fungi Myceliophth...,NaN,21964414.0,Nat Biotechnol,"Centre for Structural and Functional Genomics,...",USA
1,GSE183387,Thermothelomyces thermophilus,49,Transcriptomic insights into the roles of the ...,"Thermothelomyces thermophilus, formerly known ...",NaN,NaN,NaN,"Technische Universität Berlin, Benedikt Siebecker",Germany
2,GSE184074,Thermothelomyces thermophilus,12,Reconstruction and analysis genome-scale metab...,Myceliophthora thermophila is a thermophilic f...,"['Myceliophthora thermophila', 'genome-scale m...",35257374.0,Biotechnol Bioeng,"Tianjin institute of industrial biotechnology,...",China
3,GSE205182,Thermothelomyces thermophilus,18,"MtTRC-1, a Novel Transcription Factor, Regulat...","In thermophilic fungi, work on the ER stress a...","['ER stress', 'MtHAC-1', 'MtTRC-1', 'Mtcbh-1',...",36165620.0,Appl Environ Microbiol,"Tianjin institute of industrial biotechnology,...",China
4,GSE214002,Thermothelomyces thermophilus,8,Weimberg pathway an alternative for utilizatio...,"An alternative for utilization of D-xylose, th...","['1,2,4-Butanetriol', 'D-Xylose', 'D-Xylose de...",36691040.0,Biotechnol Biofuels Bioprod,"Tianjin institute of industrial biotechnology,...",China
5,GSE214142,Thermothelomyces thermophilus,18,PFK2/FBPase-2 is a potential target for metabo...,The PFK-2/ FBPase-2 are important regulatory e...,"['6-phosphofructo-2-kinase/fructose-2,6-biphos...",36478865.0,Front Microbiol,"Tianjin institute of industrial biotechnology,...",China
6,GSE110062,Thermothelomyces thermophilus,6,Transcriptional landscape of Myceliophthora th...,Thermophilic fungus Myceliophthora thermophila...,"['Cellulose', 'Myceliophthora thermophila', 'S...",29843921.0,Bioresour Technol,"Tianjin institute of industrial biotechnology,...",China
7,GSE111986,Thermothelomyces thermophilus,4,A novel conserved transcription factor CLR-4 r...,Fungal degradation of lignocellulosic biomass ...,NaN,30474279.0,Mol Microbiol,"Tianjin institute of industrial biotechnology,...",China
8,GSE114057,Thermothelomyces thermophilus,15,Engineering the Cellulolytic Fungus Myceliopht...,Producing the fuels and chemicals from renewab...,"['Biochemicals', 'C4-diacid', 'CRISPR/Cas9', '...",31078793.0,Metab Eng,"Tianjin institute of industrial biotechnology,...",China
9,GSE57235,Thermothelomyces thermophilus,4,Transcriptomic response to different biomass i...,The thermophilic filamentous fungi Myceliophth...,"['Biomass degradation', 'Carbohydrate-active e...",24881579.0,Fungal Genet Biol,"Centre for Structural and Functional Genomics,...",Canada
10,GSE137286,Thermothelomyces thermophilus,20,Myceliophthora thermophila Xyr1 is predominant...,The aim of this study is to investigate the ro...,"['Cellulose degradation', 'Myceliophthora ther...",31534479.0,Biotechnol Biofuels,"fungal physiology, Centre of fungal biodiversity",Netherlands
11,GSE165516,Thermothelomyces thermophilus,12,Transcriptional profiling of Myceliophthora th...,Transcriptional landscape of MyceliopTranscrip...,"['Myceliophthora', 'galactose transport', 'gal...",33995328.0,Front Microbiol,"Tianjin institute of industrial biotechnology,...",China

In [3]:
# 将df_dataset中的Keyword这一列中的[]去掉
df_dataset['Keyword'] = df_dataset['Keyword'].str.strip('[]')

df_dataset

,GEO Series,Species,Samples,Title,Summary,Keyword,Publication,Journal,Institution,Country
0,GSE27323,Thermothelomyces thermophilus,7,Transcriptomic response to substrate and tempe...,The thermophilic filamentous fungi Myceliophth...,NaN,21964414.0,Nat Biotechnol,"Centre for Structural and Functional Genomics,...",USA
1,GSE183387,Thermothelomyces thermophilus,49,Transcriptomic insights into the roles of the ...,"Thermothelomyces thermophilus, formerly known ...",NaN,NaN,NaN,"Technische Universität Berlin, Benedikt Siebecker",Germany
2,GSE184074,Thermothelomyces thermophilus,12,Reconstruction and analysis genome-scale metab...,Myceliophthora thermophila is a thermophilic f...,"'Myceliophthora thermophila', 'genome-scale me...",35257374.0,Biotechnol Bioeng,"Tianjin institute of industrial biotechnology,...",China
3,GSE205182,Thermothelomyces thermophilus,18,"MtTRC-1, a Novel Transcription Factor, Regulat...","In thermophilic fungi, work on the ER stress a...","'ER stress', 'MtHAC-1', 'MtTRC-1', 'Mtcbh-1', ...",36165620.0,Appl Environ Microbiol,"Tianjin institute of industrial biotechnology,...",China
4,GSE214002,Thermothelomyces thermophilus,8,Weimberg pathway an alternative for utilizatio...,"An alternative for utilization of D-xylose, th...","'1,2,4-Butanetriol', 'D-Xylose', 'D-Xylose deh...",36691040.0,Biotechnol Biofuels Bioprod,"Tianjin institute of industrial biotechnology,...",China
5,GSE214142,Thermothelomyces thermophilus,18,PFK2/FBPase-2 is a potential target for metabo...,The PFK-2/ FBPase-2 are important regulatory e...,"'6-phosphofructo-2-kinase/fructose-2,6-biphosp...",36478865.0,Front Microbiol,"Tianjin institute of industrial biotechnology,...",China
6,GSE110062,Thermothelomyces thermophilus,6,Transcriptional landscape of Myceliophthora th...,Thermophilic fungus Myceliophthora thermophila...,"'Cellulose', 'Myceliophthora thermophila', 'St...",29843921.0,Bioresour Technol,"Tianjin institute of industrial biotechnology,...",China
7,GSE111986,Thermothelomyces thermophilus,4,A novel conserved transcription factor CLR-4 r...,Fungal degradation of lignocellulosic biomass ...,NaN,30474279.0,Mol Microbiol,"Tianjin institute of industrial biotechnology,...",China
8,GSE114057,Thermothelomyces thermophilus,15,Engineering the Cellulolytic Fungus Myceliopht...,Producing the fuels and chemicals from renewab...,"'Biochemicals', 'C4-diacid', 'CRISPR/Cas9', 'C...",31078793.0,Metab Eng,"Tianjin institute of industrial biotechnology,...",China
9,GSE57235,Thermothelomyces thermophilus,4,Transcriptomic response to different biomass i...,The thermophilic filamentous fungi Myceliophth...,"'Biomass degradation', 'Carbohydrate-active en...",24881579.0,Fungal Genet Biol,"Centre for Structural and Functional Genomics,...",Canada
10,GSE137286,Thermothelomyces thermophilus,20,Myceliophthora thermophila Xyr1 is predominant...,The aim of this study is to investigate the ro...,"'Cellulose degradation', 'Myceliophthora therm...",31534479.0,Biotechnol Biofuels,"fungal physiology, Centre of fungal biodiversity",Netherlands
11,GSE165516,Thermothelomyces thermophilus,12,Transcriptional profiling of Myceliophthora th...,Transcriptional landscape of MyceliopTranscrip...,"'Myceliophthora', 'galactose transport', 'gala...",33995328.0,Front Microbiol,"Tianjin institute of industrial biotechnology,...",China

In [4]:
# 保存
df_dataset.to_csv('dataset.tsv', sep='\t', index=False)