In [2]:
import pandas as pd
import numpy as np
import os
import json

### 1. 生成sample_condition.tsv表

In [3]:
# 读取当前目录下的sample.tsv 
df = pd.read_csv('sample.tsv', sep='\t')
df['Time'] = df['Time'].fillna('')
df['Condition'] = df['Strain'] + ' ' + df['Carbon Sources'] + ' ' + df['Temperature'].fillna('NA') + ' ' + df['Time'].fillna('NA')
df

,Sample ID,Strain,Carbon Sources,Temperature,Time,Title,Series Accession,Related Sample,Condition
0,mt001001,wt,Barley,34°,,Comparative genomic analysis of the thermophil...,GSE27323,GSM675519,wt Barley 34°
1,mt001002,wt,Barley,45°,,Comparative genomic analysis of the thermophil...,GSE27323,"GSM675520,GSM675523",wt Barley 45°
2,mt001003,wt,Glucose,34°,,Comparative genomic analysis of the thermophil...,GSE27323,"GSM675524,GSM675525",wt Glucose 34°
3,mt001004,wt,Glucose,45°,,Comparative genomic analysis of the thermophil...,GSE27323,GSM675521,wt Glucose 45°
4,mt001005,wt,Alfalfa,45°,,Comparative genomic analysis of the thermophil...,GSE27323,GSM675522,wt Alfalfa 45°
...,...,...,...,...,...,...,...,...,...
103,mt014008,MtLat-1,Arabinan,45°,4d,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873690,GSM6873691",MtLat-1 Arabinan 45° 4d
104,mt014009,MtAra,Aarabinose,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873692,GSM6873693",MtAra Aarabinose 45° 4h
105,mt014010,MtAra,Xylose,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873694,GSM6873695",MtAra Xylose 45° 4h
106,mt014011,MtAra,Arabinan,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873696,GSM6873697",MtAra Arabinan 45° 4h
107,mt014012,wt,Arabinan,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873698,GSM6873699",wt Arabinan 45° 4h

In [4]:
# df保留Sample Number、Sample ID、Series ID、Study Title、Species、Strain、Sample Name、Canbon Sources、Temperature列
df_1 = df[['Sample ID', 'Series Accession','Title', 'Condition']]

# 如果Conditon最后一位是_，则去掉
df_1.loc[:,'Condition'] = df_1['Condition'].apply(lambda x: x[:-1] if x[-1] == '_' else x)

df_1

,Sample ID,Series Accession,Title,Condition
0,mt001001,GSE27323,Comparative genomic analysis of the thermophil...,wt Barley 34°
1,mt001002,GSE27323,Comparative genomic analysis of the thermophil...,wt Barley 45°
2,mt001003,GSE27323,Comparative genomic analysis of the thermophil...,wt Glucose 34°
3,mt001004,GSE27323,Comparative genomic analysis of the thermophil...,wt Glucose 45°
4,mt001005,GSE27323,Comparative genomic analysis of the thermophil...,wt Alfalfa 45°
...,...,...,...,...
103,mt014008,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtLat-1 Arabinan 45° 4d
104,mt014009,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra Aarabinose 45° 4h
105,mt014010,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra Xylose 45° 4h
106,mt014011,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra Arabinan 45° 4h
107,mt014012,GSE221464,The arabinose transporter MtLat-1 is involved ...,wt Arabinan 45° 4h

In [5]:
# 读取dataset.tsv
df_2 = pd.read_csv('dataset.tsv', sep='\t')
df_2 = df_2[['Series Accession', 'PMID']]

df_2.head(20)

   Series Accession        PMID
0         GSE213575  37013645.0
1         GSE213573  37013645.0
2         GSE213570  37013645.0
3         GSE221464  36966330.0
4         GSE214002  36691040.0
5         GSE214142  36478865.0
6         GSE205182  36165620.0
7         GSE184074  35257374.0
8         GSE183387         NaN
9         GSE114057  31078793.0
10        GSE111986  30474279.0
11        GSE165516  33995328.0
12        GSE110062  29843921.0
13        GSE137286  31534479.0
14         GSE57235  24881579.0
15         GSE27323  21964414.0

In [6]:
# 将df_1和df_2合并，根据Series ID列
df_3 = pd.merge(df_1, df_2, on='Series Accession', how='left')

# 重置索引
df_3 = df_3.reset_index(drop=True)

df_3['PMID'] = df_3['PMID'].astype(str)
df_3 = df_3[df_3['PMID'] != 'nan']

# PMID去掉最后两个字符
df_3['PMID'] = df_3['PMID'].apply(lambda x: x[:-2] if x[-2:] == '.0' else x)

# 保存df_3为tsv文件
df_3.to_csv('sample_condition.tsv', sep='\t', index=False)

df_3

,Sample ID,Series Accession,Title,Condition,PMID
0,mt001001,GSE27323,Comparative genomic analysis of the thermophil...,wt Barley 34°,21964414
1,mt001002,GSE27323,Comparative genomic analysis of the thermophil...,wt Barley 45°,21964414
2,mt001003,GSE27323,Comparative genomic analysis of the thermophil...,wt Glucose 34°,21964414
3,mt001004,GSE27323,Comparative genomic analysis of the thermophil...,wt Glucose 45°,21964414
4,mt001005,GSE27323,Comparative genomic analysis of the thermophil...,wt Alfalfa 45°,21964414
...,...,...,...,...,...
103,mt014008,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtLat-1 Arabinan 45° 4d,36966330
104,mt014009,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra Aarabinose 45° 4h,36966330
105,mt014010,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra Xylose 45° 4h,36966330
106,mt014011,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra Arabinan 45° 4h,36966330
107,mt014012,GSE221464,The arabinose transporter MtLat-1 is involved ...,wt Arabinan 45° 4h,36966330

### 2. 根据基因id获取按文献分类的Exp

In [10]:
def get_gene_exp(gene):
    """
    根据基因id，返回该基因在各个文献对应样本的TPM表达量
    """

    df_exp_fname = pd.read_csv('exp.tsv', sep='\t')
    df_condition = pd.read_csv('sample_condition.tsv', sep='\t')

    # 根据gene id从df_exp_fname中取出对应的行
    df = df_exp_fname[df_exp_fname['Gene id'] == gene].copy()
    # df.iloc[:, 1:] = df.iloc[:, 1:].applymap(lambda x: np.log2(x + 1)).round(2)

    # 根据基因ID从exp表中，取出该基因在各个样本的表达量
    df_condition['Sample Exp'] = df_condition['Sample ID'].map(df.set_index('Gene id').iloc[:, 0:].T.to_dict()[gene])

    # df_condition返回的是一个dataframe；构造字典
    output_dict = {
        # 'gene_info': {
        'gene_id': {
            'gene_id': gene
        }
    }
    for _, row in df_condition.iterrows():
        pmid = str(row['PMID'])   # 原先是Publications，改叫为PMID
        if pmid not in output_dict['gene_id']:
            output_dict['gene_id'][pmid] = {
                'PMID': pmid,
                'Title': row['Title'],
            }
        sample_number = row['Sample ID']
        output_dict['gene_id'][pmid][sample_number] = {
            'Sample ID': sample_number,
            'Condition': row['Condition'],
            # 'Exp': str(row['Sample Exp'])
            'Exp': row['Sample Exp']
        }
    
    # # output_dict转为json格式
    # output_json = json.dumps(output_dict, indent=4)
    
    return output_dict

dict_gene_exp = get_gene_exp('MYCTH_101575')
dict_gene_exp

{'gene_id': {'gene_id': 'MYCTH_101575',
  '21964414': {'PMID': '21964414',
   'Title': 'Comparative genomic analysis of the thermophilic biomass-degrading fungi Myceliophthora thermophila and Thielavia terrestris.',
   'mt001001': {'Sample ID': 'mt001001',
    'Condition': 'wt Barley 34° ',
    'Exp': 13.59},
   'mt001002': {'Sample ID': 'mt001002',
    'Condition': 'wt Barley 45° ',
    'Exp': 4.45},
   'mt001003': {'Sample ID': 'mt001003',
    'Condition': 'wt Glucose 34° ',
    'Exp': 10.71},
   'mt001004': {'Sample ID': 'mt001004',
    'Condition': 'wt Glucose 45° ',
    'Exp': 3.92},
   'mt001005': {'Sample ID': 'mt001005',
    'Condition': 'wt Alfalfa 45° ',
    'Exp': 4.87}},
  '24881579': {'PMID': '24881579',
   'Title': 'Transcriptome and exoproteome analysis of utilization of plant-derived biomass by Myceliophthora thermophila.',
   'mt002001': {'Sample ID': 'mt002001',
    'Condition': 'wt Oat 45° early growth stage',
    'Exp': 4.78},
   'mt002002': {'Sample ID': 'mt002002',
    'Condition': 'wt Triticale 45° early growth stage',
    'Exp': 3.17},
   'mt002003': {'Sample ID': 'mt002003',
    'Condition': 'wt Canola 45° early growth stage',
    'Exp': 3.39},
   'mt002004': {'Sample ID': 'mt002004',
    'Condition': 'wt Flax 45° early growth stage',
    'Exp': 3.24}},
  '29843921': {'PMID': '29843921',
   'Title': 'Transcriptional analysis of Myceliophthora thermophila on soluble starch and role of regulator AmyR on polysaccharide degradation.',
   'mt003001': {'Sample ID': 'mt003001',
    'Condition': 'wt NoCarbon 45° 4h',
    'Exp': 5.61},
   'mt003002': {'Sample ID': 'mt003002',
    'Condition': 'wt Glucose 45° 4h',
    'Exp': 1.52},
   'mt003003': {'Sample ID': 'mt003003',
    'Condition': 'wt Starch 45° 4h',
    'Exp': 2.97}},
  '31534479': {'PMID': '31534479',
   'Title': 'Myceliophthora thermophila Xyr1 is predominantly involved in xylan degradation and xylose catabolism.',
   'mt004001': {'Sample ID': 'mt004001',
    'Condition': 'wt Glucose 37° 2h',
    'Exp': 10.72},
   'mt004002': {'Sample ID': 'mt004002',
    'Condition': 'wt Xylose 37° 2h',
    'Exp': 5.05},
   'mt004003': {'Sample ID': 'mt004003',
    'Condition': 'wt Arabinose 37° 2h',
    'Exp': 4.97},
   'mt004004': {'Sample ID': 'mt004004',
    'Condition': 'wt Arabinoxylan 37° 2h',
    'Exp': 5.29},
   'mt004005': {'Sample ID': 'mt004005',
    'Condition': 'wt Arabinoxylan 37° 8h',
    'Exp': 8.61},
   'mt004006': {'Sample ID': 'mt004006',
    'Condition': 'Xyr1 mutant Glucose 37° 2h',
    'Exp': 10.47},
   'mt004007': {'Sample ID': 'mt004007',
    'Condition': 'Xyr1 mutant Xylose 37° 2h',
    'Exp': 4.5},
   'mt004008': {'Sample ID': 'mt004008',
    'Condition': 'Xyr1 mutant Arabinose 37° 2h',
    'Exp': 7.74},
   'mt004009': {'Sample ID': 'mt004009',
    'Condition': 'Xyr1 mutant Arabinoxylan 37° 2h',
    'Exp': 8.44},
   'mt004010': {'Sample ID': 'mt004010',
    'Condition': 'Xyr1 mutant Arabinoxylan 37° 8h',
    'Exp': 5.93}},
  '30474279': {'PMID': '30474279',
   'Title': 'CLR-4, a novel conserved transcription factor for cellulase gene expression in ascomycete fungi.',
   'mt005001': {'Sample ID': 'mt005001',
    'Condition': 'Mtclr NoCarbon 45° 4h',
    'Exp': 7.08},
   'mt005002': {'Sample ID': 'mt005002',
    'Condition': 'wt NoCarbon 45° 4h',
    'Exp': 2.93}},
  '31078793': {'PMID': '31078793',
   'Title': 'Direct production of commodity chemicals from lignocellulose using Myceliophthora thermophila.',
   'mt006001': {'Sample ID': 'mt006001',
    'Condition': 'wt Avicel 45° 2 or 4d',
    'Exp': 7.67},
   'mt006002': {'Sample ID': 'mt006002',
    'Condition': 'JG141 Avicel 45° 2 or 4d',
    'Exp': 7.97},
   'mt006003': {'Sample ID': 'mt006003',
    'Condition': 'JG207 Avicel 45° 2 or 4d',
    'Exp': 4.78},
   'mt006004': {'Sample ID': 'mt006004',
    'Condition': 'JG207Ncclr2 Avicel 45° 2 or 4d',
    'Exp': 7.85},
   'mt006005': {'Sample ID': 'mt006005',
    'Condition': 'JG336 Avicel 45° 2 or 4d',
    'Exp': 3.25},
   'mt006006': {'Sample ID': 'mt006006',
    'Condition': 'wt Glucose 45° 2 or 4d',
    'Exp': 9.08},
   'mt006007': {'Sample ID': 'mt006007',
    'Condition': 'JG207 Glucose 45° 2 or 4d',
    'Exp': 6.12}},
  '33995328': {'PMID': '33995328',
   'Title': 'Transcriptional Profiling of Myceliophthora thermophila on Galactose and Metabolic Engineering for Improved Galactose Utilization.',
   'mt007001': {'Sample ID': 'mt007001',
    'Condition': 'wt NoCarbon 45° 4h',
    'Exp': 3.03},
   'mt007002': {'Sample ID': 'mt007002',
    'Condition': 'wt Glucose 45° 4h',
    'Exp': 2.83},
   'mt007003': {'Sample ID': 'mt007003',
    'Condition': 'wt Galatose 45° 4h',
    'Exp': 5.32},
   'mt007004': {'Sample ID': 'mt007004',
    'Condition': 'wt Galatose 45° 4h',
    'Exp': 5.66},
   'mt007005': {'Sample ID': 'mt007005',
    'Condition': 'OEgal2 Galatose 45° 4h',
    'Exp': 3.43},
   'mt007006': {'Sample ID': 'mt007006',
    'Condition': 'OEgal2 Galatose 45° 4h',
    'Exp': 20.16}},
  '36478865': {'PMID': '36478865',
   'Title': 'PFK2/FBPase-2 is a potential target for metabolic engineering in the filamentous fungus Myceliophthora thermophila.',
   'mt009001': {'Sample ID': 'mt009001',
    'Condition': 'wt Glucose 45° 2d',
    'Exp': 8.01},
   'mt009002': {'Sample ID': 'mt009002',
    'Condition': 'wt Glucose 45° 4d',
    'Exp': 9.24},
   'mt009003': {'Sample ID': 'mt009003',
    'Condition': 'Δpfk2 Glucose 45° 2d',
    'Exp': 3.87},
   'mt009004': {'Sample ID': 'mt009004',
    'Condition': 'Δpfk2 Glucose 45° 4d',
    'Exp': 6.95},
   'mt009005': {'Sample ID': 'mt009005',
    'Condition': 'Δpfk2 Glucose 45° 2d',
    'Exp': 10.62},
   'mt009006': {'Sample ID': 'mt009006',
    'Condition': 'Δpfk2 Glucose 45° 2d',
    'Exp': 10.27},
   'mt009007': {'Sample ID': 'mt009007',
    'Condition': 'Δpfk2 Glucose 45° 4d',
    'Exp': 12.38},
   'mt009008': {'Sample ID': 'mt009008',
    'Condition': 'Δpfk2 Glucose 45° 2d',
    'Exp': 9.07},
   'mt009009': {'Sample ID': 'mt009009',
    'Condition': 'Δpfk2 Glucose 45° 4d',
    'Exp': 12.45}},
  '35257374': {'PMID': '35257374',
   'Title': 'Reconstruction and analysis of genome-scale metabolic model for thermophilic fungus Myceliophthora thermophila.',
   'mt010001': {'Sample ID': 'mt010001',
    'Condition': 'wt Glucose 35° 66h',
    'Exp': 5.15},
   'mt010002': {'Sample ID': 'mt010002',
    'Condition': 'wt Glucose 40° 40h',
    'Exp': 3.55},
   'mt010003': {'Sample ID': 'mt010003',
    'Condition': 'wt Glucose 45° 40h',
    'Exp': 6.15},
   'mt010004': {'Sample ID': 'mt010004',
    'Condition': 'wt Glucose 50° 40h',
    'Exp': 5.13}},
  '36165620': {'PMID': '36165620',
   'Title': 'MtTRC-1, a Novel Transcription Factor, Regulates Cellulase Production via Directly Modulating the Genes Expression of the Mthac-1 and Mtcbh-1 in Myceliophthora thermophila.',
   'mt011001': {'Sample ID': 'mt011001',
    'Condition': 'ΔMycth_90344 Avicel 45° 4h',
    'Exp': 1.58},
   'mt011002': {'Sample ID': 'mt011002',
    'Condition': 'ΔMycth_90344 Avicel 45° 6h',
    'Exp': 4.48},
   'mt011003': {'Sample ID': 'mt011003',
    'Condition': 'ΔMycth_90344 Starch 45° 4h',
    'Exp': 2.49},
   'mt011004': {'Sample ID': 'mt011004',
    'Condition': 'wt Avicel 45° 4h',
    'Exp': 1.14},
   'mt011005': {'Sample ID': 'mt011005',
    'Condition': 'wt Avicel 45° 6h',
    'Exp': 2.47},
   'mt011006': {'Sample ID': 'mt011006',
    'Condition': 'wt Starch 45° 4h',
    'Exp': 2.97}},
  '37013645': {'PMID': '37013645',
   'Title': 'The putative methyltransferase LaeA regulates mycelium growth and cellulase production in Myceliophthora thermophila.',
   'mt012001': {'Sample ID': 'mt012001',
    'Condition': 'wt Glucose 45° 24h',
    'Exp': 2.76},
   'mt012002': {'Sample ID': 'mt012002',
    'Condition': 'ΔlaeA Glucose 45° 24h',
    'Exp': 2.89},
   'mt012003': {'Sample ID': 'mt012003',
    'Condition': 'Δgrf Glucose 45° 24h',
    'Exp': 5.5},
   'mt012004': {'Sample ID': 'mt012004',
    'Condition': 'Δgrf Glucose 45° 24h',
    'Exp': 5.28},
   'mt012005': {'Sample ID': 'mt012005',
    'Condition': 'Δgrf Glucose 45° 24h',
    'Exp': 4.52},
   'mt012006': {'Sample ID': 'mt012006',
    'Condition': 'Δcre Glucose 45° 24h',
    'Exp': 1.37},
   'mt012007': {'Sample ID': 'mt012007',
    'Condition': 'wt Avicel 45° 2d',
    'Exp': 5.44},
   'mt012008': {'Sample ID': 'mt012008',
    'Condition': 'ΔlaeA Avicel 45° 2d',
    'Exp': 5.17},
   'mt012009': {'Sample ID': 'mt012009',
    'Condition': 'wt Avicel 45° 4d',
    'Exp': 4.69},
   'mt012010': {'Sample ID': 'mt012010',
    'Condition': 'ΔlaeA Avicel 45° 4d',
    'Exp': 7.83},
   'mt012011': {'Sample ID': 'mt012011',
    'Condition': 'wt Avicel 45° 6d',
    'Exp': 13.19},
   'mt012012': {'Sample ID': 'mt012012',
    'Condition': 'ΔlaeA Avicel 45° 6d',
    'Exp': 11.3}},
  '36691040': {'PMID': '36691040',
   'Title': 'The Weimberg pathway: an alternative for Myceliophthora thermophila to utilize D-xylose.',
   'mt013001': {'Sample ID': 'mt013001',
    'Condition': 'JG207 Xylose 45° 4h',
    'Exp': 3.78},
   'mt013002': {'Sample ID': 'mt013002',
    'Condition': 'DF1102 Xylose 45° 4h',
    'Exp': 7.47},
   'mt013003': {'Sample ID': 'mt013003',
    'Condition': 'DF1406 Xylose 45° 4h',
    'Exp': 3.78},
   'mt013004': {'Sample ID': 'mt013004',
    'Condition': 'DF1501 Xylose 45° 4h',
    'Exp': 4.57}},
  '36966330': {'PMID': '36966330',
   'Title': 'The arabinose transporter MtLat-1 is involved in hemicellulase repression as a pentose transceptor in Myceliophthora thermophila.',
   'mt014001': {'Sample ID': 'mt014001',
    'Condition': 'wt NoCarbon 45° 4h',
    'Exp': 3.03},
   'mt014002': {'Sample ID': 'mt014002',
    'Condition': 'wt Glucose 45° 4h',
    'Exp': 2.83},
   'mt014003': {'Sample ID': 'mt014003',
    'Condition': 'wt Xylose 45° 4h',
    'Exp': 4.0},
   'mt014004': {'Sample ID': 'mt014004',
    'Condition': 'wt Aarabinose 45° 4h',
    'Exp': 7.92},
   'mt014005': {'Sample ID': 'mt014005',
    'Condition': 'wt Arabinan 45° 2d',
    'Exp': 3.84},
   'mt014006': {'Sample ID': 'mt014006',
    'Condition': 'wt Arabinan 45° 4d',
    'Exp': 5.56},
   'mt014007': {'Sample ID': 'mt014007',
    'Condition': 'MtLat-1 Arabinan 45° 2d',
    'Exp': 4.25},
   'mt014008': {'Sample ID': 'mt014008',
    'Condition': 'MtLat-1 Arabinan 45° 4d',
    'Exp': 5.85},
   'mt014009': {'Sample ID': 'mt014009',
    'Condition': 'MtAra Aarabinose 45° 4h',
    'Exp': 13.76},
   'mt014010': {'Sample ID': 'mt014010',
    'Condition': 'MtAra Xylose 45° 4h',
    'Exp': 9.27},
   'mt014011': {'Sample ID': 'mt014011',
    'Condition': 'MtAra Arabinan 45° 4h',
    'Exp': 1.73},
   'mt014012': {'Sample ID': 'mt014012',
    'Condition': 'wt Arabinan 45° 4h',
    'Exp': 0.98}}}}

In [11]:
#将output_dict 转为json文件
with open('gene_exp.json', 'w') as f:
    json.dump(dict_gene_exp, f, indent=4)