In [2]:
import pandas as pd


df_sample = pd.read_csv('sample.tsv', sep='\t')
df_sample

,Sample Number,Sample ID,Run,Series ID,Study Title,Species,Strain,Model,Library Strategy,Sample Name,Carbon Sources,Temperature
0,F01001001,GSM675519,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_34C_rep1,Barley,34°
1,F01001002,GSM675520,SRR101402,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
2,F01001003,GSM675521,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Glucose_45C_rep1,Glucose,45°
3,F01001004,GSM675522,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Alfalfa_45C_rep1,Alfalfa,45°
4,F01001005,GSM675523,SRR101405,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
...,...,...,...,...,...,...,...,...,...,...,...,...
168,F01012004,GSM5035235,SRR13529932,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,WTdeltagalK-Gal-2,Gal,45°
169,F01012005,GSM5035236,SRR13529933,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2-Gal-1,Gal,45°
170,F01012005,GSM5035237,SRR13529934,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2-Gal-2,Gal,45°
171,F01012006,GSM5035238,SRR13529935,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2deltagalK-Gal-1,Gal,45°
172,F01012006,GSM5035239,SRR13529936,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2detalgalK-Gal-2,Gal,45°

In [3]:
# 删除Sample Name这一列中的Myceliophthora_thermophila_
df_sample['Sample Name'] = df_sample['Sample Name'].str.replace('Myceliophthora_thermophila_', '')
df_sample['Sample Name'] = df_sample['Sample Name'].str.replace('Myceliphothora thermophila ', '')


# 将Species这一列Thermothelomyces thermophilus改为Myceliophthora thermophila
df_sample['Species'] = df_sample['Species'].str.replace('Thermothelomyces thermophilus ', 'Myceliphothora thermophila')

In [4]:
# df_sample中，Sample Number这一列有重复值，将重复值的行合并,其中Study Title这一列用；分开
df_sample = df_sample.groupby('Sample Number').agg({
    'Sample ID':lambda x: ','.join(x),
    'Run':lambda x: ','.join(x),
    'Series ID':lambda x: ','.join(x),
    'Study Title':lambda x: ';'.join(x),
    'Species':lambda x: ','.join(x),
    'Strain':lambda x: ','.join(x),
    'Model':lambda x: ','.join(x),
    'Library Strategy':lambda x: ','.join(x),
    'Sample Name':lambda x: ','.join(x),
    'Carbon Sources':lambda x: ','.join(x),
    'Temperature':lambda x: ','.join(x),

    }).reset_index()

df_sample

,Sample Number,Sample ID,Run,Series ID,Study Title,Species,Strain,Model,Library Strategy,Sample Name,Carbon Sources,Temperature
0,F01001001,GSM675519,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_34C_rep1,Barley,34°
1,F01001002,GSM675520,SRR101402,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
2,F01001003,GSM675521,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Glucose_45C_rep1,Glucose,45°
3,F01001004,GSM675522,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Alfalfa_45C_rep1,Alfalfa,45°
4,F01001005,GSM675523,SRR101405,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
...,...,...,...,...,...,...,...,...,...,...,...,...
81,F01012002,"GSM5035230,GSM5035231","SRR13529927,SRR13529928","GSE165516,GSE165516",Transcriptional profiling of Myceliophthora th...,"Myceliphothora thermophila,Myceliphothora ther...","ATCC 42464,ATCC 42464","Illumina HiSeq 2000,Illumina HiSeq 2000","RNA-Seq,RNA-Seq","WT-Glu-1,WT-Glu-2","Glucose,Glucose","45°,45°"
82,F01012003,"GSM5035232,GSM5035233","SRR13529929,SRR13529930","GSE165516,GSE165516",Transcriptional profiling of Myceliophthora th...,"Myceliphothora thermophila,Myceliphothora ther...","ATCC 42464,ATCC 42464","Illumina HiSeq 2000,Illumina HiSeq 2000","RNA-Seq,RNA-Seq","WT-Gal-1,WT-Gal-2","Gal,Gal","45°,45°"
83,F01012004,"GSM5035234,GSM5035235","SRR13529931,SRR13529932","GSE165516,GSE165516",Transcriptional profiling of Myceliophthora th...,"Myceliphothora thermophila,Myceliphothora ther...","ATCC 42464,ATCC 42464","Illumina HiSeq 2000,Illumina HiSeq 2000","RNA-Seq,RNA-Seq","WTdeltagalK-Gal-1,WTdeltagalK-Gal-2","Gal,Gal","45°,45°"
84,F01012005,"GSM5035236,GSM5035237","SRR13529933,SRR13529934","GSE165516,GSE165516",Transcriptional profiling of Myceliophthora th...,"Myceliphothora thermophila,Myceliphothora ther...","ATCC 42464,ATCC 42464","Illumina HiSeq 2000,Illumina HiSeq 2000","RNA-Seq,RNA-Seq","OEgal2-Gal-1,OEgal2-Gal-2","Gal,Gal","45°,45°"
85,F01012006,"GSM5035238,GSM5035239","SRR13529935,SRR13529936","GSE165516,GSE165516",Transcriptional profiling of Myceliophthora th...,"Myceliphothora thermophila,Myceliphothora ther...","ATCC 42464,ATCC 42464","Illumina HiSeq 2000,Illumina HiSeq 2000","RNA-Seq,RNA-Seq","OEgal2deltagalK-Gal-1,OEgal2detalgalK-Gal-2","Gal,Gal","45°,45°"

In [5]:
# Series ID这一列中，存在多个值，如果值相同则值合并
df_sample['Series ID'] = df_sample['Series ID'].str.split(',').str[0]
df_sample['Study Title'] = df_sample['Study Title'].str.split(';').str[0]
df_sample['Species'] = df_sample['Species'].str.split(',').str[0]
df_sample['Strain'] = df_sample['Strain'].str.split(',').str[0]
df_sample['Model'] = df_sample['Model'].str.split(',').str[0]
df_sample['Library Strategy'] = df_sample['Library Strategy'].str.split(',').str[0]
df_sample['Carbon Sources'] = df_sample['Carbon Sources'].str.split(',').str[0]
df_sample['Temperature'] = df_sample['Temperature'].str.split(',').str[0]

df_sample

,Sample Number,Sample ID,Run,Series ID,Study Title,Species,Strain,Model,Library Strategy,Sample Name,Carbon Sources,Temperature
0,F01001001,GSM675519,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_34C_rep1,Barley,34°
1,F01001002,GSM675520,SRR101402,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
2,F01001003,GSM675521,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Glucose_45C_rep1,Glucose,45°
3,F01001004,GSM675522,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Alfalfa_45C_rep1,Alfalfa,45°
4,F01001005,GSM675523,SRR101405,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
...,...,...,...,...,...,...,...,...,...,...,...,...
81,F01012002,"GSM5035230,GSM5035231","SRR13529927,SRR13529928",GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,"WT-Glu-1,WT-Glu-2",Glucose,45°
82,F01012003,"GSM5035232,GSM5035233","SRR13529929,SRR13529930",GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,"WT-Gal-1,WT-Gal-2",Gal,45°
83,F01012004,"GSM5035234,GSM5035235","SRR13529931,SRR13529932",GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,"WTdeltagalK-Gal-1,WTdeltagalK-Gal-2",Gal,45°
84,F01012005,"GSM5035236,GSM5035237","SRR13529933,SRR13529934",GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,"OEgal2-Gal-1,OEgal2-Gal-2",Gal,45°
85,F01012006,"GSM5035238,GSM5035239","SRR13529935,SRR13529936",GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,"OEgal2deltagalK-Gal-1,OEgal2detalgalK-Gal-2",Gal,45°

In [6]:
# 保存
df_sample.to_csv('sample_fname.tsv', sep='\t', index=False)