In [10]:
import pandas as pd


df_sample = pd.read_csv('sample.tsv', sep='\t')
df_sample

,Sample Number,Sample ID,Run,Series ID,Study Title,Species,Strain,Model,Library Strategy,Sample Name,Carbon Sources,Temperature
0,F01001001,GSM675519,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_34C_rep1,Barley,34°
1,F01001002,GSM675520,SRR101402,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
2,F01001003,GSM675521,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Glucose_45C_rep1,Glucose,45°
3,F01001004,GSM675522,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Alfalfa_45C_rep1,Alfalfa,45°
4,F01001005,GSM675523,SRR101405,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
...,...,...,...,...,...,...,...,...,...,...,...,...
168,F01012004,GSM5035235,SRR13529932,GSE165516,Transcriptional profiling of Myceliophthora th...,Thermothelomyces thermophilus,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,WTdeltagalK-Gal-2,Gal,45°
169,F01012005,GSM5035236,SRR13529933,GSE165516,Transcriptional profiling of Myceliophthora th...,Thermothelomyces thermophilus,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2-Gal-1,Gal,45°
170,F01012005,GSM5035237,SRR13529934,GSE165516,Transcriptional profiling of Myceliophthora th...,Thermothelomyces thermophilus,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2-Gal-2,Gal,45°
171,F01012006,GSM5035238,SRR13529935,GSE165516,Transcriptional profiling of Myceliophthora th...,Thermothelomyces thermophilus,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2deltagalK-Gal-1,Gal,45°
172,F01012006,GSM5035239,SRR13529936,GSE165516,Transcriptional profiling of Myceliophthora th...,Thermothelomyces thermophilus,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2detalgalK-Gal-2,Gal,45°

In [13]:
# 删除Sample Name这一列中的Myceliophthora_thermophila_
df_sample['Sample Name'] = df_sample['Sample Name'].str.replace('Myceliophthora_thermophila_', '')
df_sample['Sample Name'] = df_sample['Sample Name'].str.replace('Myceliphothora thermophila ', '')


# 将Species这一列Thermothelomyces thermophilus改为Myceliophthora thermophila
df_sample['Species'] = df_sample['Species'].str.replace('Thermothelomyces thermophilus ', 'Myceliphothora thermophila')

In [14]:
df_sample

,Sample Number,Sample ID,Run,Series ID,Study Title,Species,Strain,Model,Library Strategy,Sample Name,Carbon Sources,Temperature
0,F01001001,GSM675519,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_34C_rep1,Barley,34°
1,F01001002,GSM675520,SRR101402,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
2,F01001003,GSM675521,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Glucose_45C_rep1,Glucose,45°
3,F01001004,GSM675522,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Alfalfa_45C_rep1,Alfalfa,45°
4,F01001005,GSM675523,SRR101405,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,ATCC 42464,Illumina Genome Analyzer II,RNA-Seq,Barley_45C_rep1,Barley,45°
...,...,...,...,...,...,...,...,...,...,...,...,...
168,F01012004,GSM5035235,SRR13529932,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,WTdeltagalK-Gal-2,Gal,45°
169,F01012005,GSM5035236,SRR13529933,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2-Gal-1,Gal,45°
170,F01012005,GSM5035237,SRR13529934,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2-Gal-2,Gal,45°
171,F01012006,GSM5035238,SRR13529935,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2deltagalK-Gal-1,Gal,45°
172,F01012006,GSM5035239,SRR13529936,GSE165516,Transcriptional profiling of Myceliophthora th...,Myceliphothora thermophila,ATCC 42464,Illumina HiSeq 2000,RNA-Seq,OEgal2detalgalK-Gal-2,Gal,45°

In [15]:
# 保存
df_sample.to_csv('sample.tsv', sep='\t', index=False)