In [1]:
import pandas as pd


# df_sample = pd.read_csv('sample.tsv', sep='\t')
df_sample = pd.read_excel('sample.xlsx')
df_sample

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Model,Library Seletion,Library Source,Library Strategy,Samples,Strain,Carbon Sources,Temperature,Time,Year
0,mt001001,GSM675519,SRX043463,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Barley_34C_rep1,wt,Barley,34°,NaN,2011 Oct
1,mt001002,GSM675520,SRX043464,SRR101402,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Barley_45C_rep1,wt,Barley,45°,NaN,2011 Oct
2,mt001004,GSM675521,SRX043465,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Glucose_45C_rep1,wt,Glucose,45°,NaN,2011 Oct
3,mt001005,GSM675522,SRX043466,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Alfalfa_45C_rep1,wt,Alfalfa,45°,NaN,2011 Oct
4,mt001002,GSM675523,SRX043467,SRR101405,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Barley_45C_rep2,wt,Barley,45°,NaN,2011 Oct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,mt014010,GSM6873695,SRX18797668,SRR22838472,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,MtAra-1_xylose_4h_2,MtAra,Xylose,45°,4h,2023 Mar
217,mt014011,GSM6873696,SRX18797669,SRR22838471,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,MtAra-1_arabinan_4h_1,MtAra,Arabinan,45°,4h,2023 Mar
218,mt014011,GSM6873697,SRX18797670,SRR22838470,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,MtAra-1_arabinan_4h_2,MtAra,Arabinan,45°,4h,2023 Mar
219,mt014012,GSM6873698,SRX18797671,SRR22838469,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,WT_arabinan_4h_1,wt,Arabinan,45°,4h,2023 Mar
220,mt014012,GSM6873699,SRX18797672,SRR22838468,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,WT_arabinan_4h_2,wt,Arabinan,45°,4h,2023 Mar

In [2]:
# 删除Samples这一列中的Myceliophthora_thermophila_
df_sample['Samples'] = df_sample['Samples'].str.replace('Myceliophthora_thermophila_', '')
df_sample['Samples'] = df_sample['Samples'].str.replace('Myceliphothora thermophila ', '')


# 将Species这一列Thermothelomyces thermophilus改为Myceliophthora thermophila
df_sample['Species'] = df_sample['Species'].str.replace('Thermothelomyces thermophilus', 'Myceliphothora thermophila')

df_sample['Time'] = df_sample['Time'].fillna('')

df_sample

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Model,Library Seletion,Library Source,Library Strategy,Samples,Strain,Carbon Sources,Temperature,Time,Year
0,mt001001,GSM675519,SRX043463,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Barley_34C_rep1,wt,Barley,34°,,2011 Oct
1,mt001002,GSM675520,SRX043464,SRR101402,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Barley_45C_rep1,wt,Barley,45°,,2011 Oct
2,mt001004,GSM675521,SRX043465,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Glucose_45C_rep1,wt,Glucose,45°,,2011 Oct
3,mt001005,GSM675522,SRX043466,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Alfalfa_45C_rep1,wt,Alfalfa,45°,,2011 Oct
4,mt001002,GSM675523,SRX043467,SRR101405,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Barley_45C_rep2,wt,Barley,45°,,2011 Oct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,mt014010,GSM6873695,SRX18797668,SRR22838472,GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,MtAra-1_xylose_4h_2,MtAra,Xylose,45°,4h,2023 Mar
217,mt014011,GSM6873696,SRX18797669,SRR22838471,GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,MtAra-1_arabinan_4h_1,MtAra,Arabinan,45°,4h,2023 Mar
218,mt014011,GSM6873697,SRX18797670,SRR22838470,GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,MtAra-1_arabinan_4h_2,MtAra,Arabinan,45°,4h,2023 Mar
219,mt014012,GSM6873698,SRX18797671,SRR22838469,GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,WT_arabinan_4h_1,wt,Arabinan,45°,4h,2023 Mar
220,mt014012,GSM6873699,SRX18797672,SRR22838468,GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,WT_arabinan_4h_2,wt,Arabinan,45°,4h,2023 Mar

In [3]:
df_sample_change = df_sample.groupby('Sample ID').agg({
    'Sample Name':lambda x: ','.join(x),
    'Experiment':lambda x: ','.join(x),
    'Run':lambda x: ','.join(x),
    'Series Accession':lambda x: ','.join(x),
    'Study Title':lambda x: ';'.join(x),
    'Species':lambda x: ','.join(x),
    'Model':lambda x: ','.join(x),
    'Library Seletion':lambda x: ','.join(x),
    'Library Source':lambda x: ','.join(x),
    'Library Strategy':lambda x: ','.join(x),
    'Samples':lambda x: ','.join(x),
    'Strain':lambda x: ','.join(x),
    'Carbon Sources':lambda x: ','.join(x),
    'Temperature':lambda x: ','.join(x),
    'Time':lambda x: ','.join(x),
    'Year':lambda x: ','.join(x),
    }).reset_index()

# 显示处理后的结果
df_sample_change

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Model,Library Seletion,Library Source,Library Strategy,Samples,Strain,Carbon Sources,Temperature,Time,Year
0,mt001001,GSM675519,SRX043463,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Barley_34C_rep1,wt,Barley,34°,,2011 Oct
1,mt001002,"GSM675520,GSM675523","SRX043464, SRX043467","SRR101402,SRR101405","GSE27323,GSE27323",Transcriptomic response to substrate and tempe...,"Myceliphothora thermophila,Myceliphothora ther...","Illumina Genome Analyzer II,Illumina Genome An...","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","Barley_45C_rep1,Barley_45C_rep2","wt,wt","Barley,Barley","45°,45°",",","2011 Oct,2011 Oct"
2,mt001003,"GSM675524,GSM675525","SRX043468, SRX043469","SRR101406,SRR101407","GSE27323,GSE27323",Transcriptomic response to substrate and tempe...,"Myceliphothora thermophila,Myceliphothora ther...","Illumina Genome Analyzer II,Illumina Genome An...","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","Glucose_34C_rep1,Glucose_45C_rep2","wt,wt","Glucose,Glucose","34°,45°",",","2011 Oct,2011 Oct"
3,mt001004,GSM675521,SRX043465,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Glucose_45C_rep1,wt,Glucose,45°,,2011 Oct
4,mt001005,GSM675522,SRX043466,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Alfalfa_45C_rep1,wt,Alfalfa,45°,,2011 Oct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,mt014008,"GSM6873690,GSM6873691","SRX18797663, SRX18797664","SRR22838477,SRR22838476","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","MtLat-1_arabinan_4d_1,MtLat-1_arabinan_4d_2","MtLat-1,MtLat-1","Arabinan,Arabinan","45°,45°","4d,4d","2023 Mar,2023 Mar"
104,mt014009,"GSM6873692,GSM6873693","SRX18797665, SRX18797666","SRR22838475,SRR22838474","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","MtAra-1_arabinose_4h_1,MtAra-1_arabinose_4h_2","MtAra,MtAra","Aarabinose,Aarabinose","45°,45°","4h,4h","2023 Mar,2023 Mar"
105,mt014010,"GSM6873694,GSM6873695","SRX18797667, SRX18797668","SRR22838473,SRR22838472","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","MtAra-1_xylose_4h_1,MtAra-1_xylose_4h_2","MtAra,MtAra","Xylose,Xylose","45°,45°","4h,4h","2023 Mar,2023 Mar"
106,mt014011,"GSM6873696,GSM6873697","SRX18797669, SRX18797670","SRR22838471,SRR22838470","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","MtAra-1_arabinan_4h_1,MtAra-1_arabinan_4h_2","MtAra,MtAra","Arabinan,Arabinan","45°,45°","4h,4h","2023 Mar,2023 Mar"
107,mt014012,"GSM6873698,GSM6873699","SRX18797671, SRX18797672","SRR22838469,SRR22838468","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","WT_arabinan_4h_1,WT_arabinan_4h_2","wt,wt","Arabinan,Arabinan","45°,45°","4h,4h","2023 Mar,2023 Mar"

In [4]:
# Series ID这一列中，存在多个值，如果值相同则值合并
df_sample_change['Series Accession'] = df_sample_change['Series Accession'].str.split(',').str[0]
df_sample_change['Study Title'] = df_sample_change['Study Title'].str.split(';').str[0]
df_sample_change['Species'] = df_sample_change['Species'].str.split(',').str[0]
df_sample_change['Strain'] = df_sample_change['Strain'].str.split(',').str[0]
df_sample_change['Model'] = df_sample_change['Model'].str.split(',').str[0]
df_sample_change['Library Seletion'] = df_sample_change['Library Seletion'].str.split(',').str[0]
df_sample_change['Library Source'] = df_sample_change['Library Source'].str.split(',').str[0]
df_sample_change['Library Strategy'] = df_sample_change['Library Strategy'].str.split(',').str[0]
df_sample_change['Strain'] = df_sample_change['Strain'].str.split(',').str[0]
df_sample_change['Carbon Sources'] = df_sample_change['Carbon Sources'].str.split(',').str[0]
df_sample_change['Temperature'] = df_sample_change['Temperature'].str.split(',').str[0]
df_sample_change['Time'] = df_sample_change['Time'].str.split(',').str[0]
df_sample_change['Year'] = df_sample_change['Year'].str.split(',').str[0]

df_sample_change

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Model,Library Seletion,Library Source,Library Strategy,Samples,Strain,Carbon Sources,Temperature,Time,Year
0,mt001001,GSM675519,SRX043463,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Barley_34C_rep1,wt,Barley,34°,,2011 Oct
1,mt001002,"GSM675520,GSM675523","SRX043464, SRX043467","SRR101402,SRR101405",GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,"Barley_45C_rep1,Barley_45C_rep2",wt,Barley,45°,,2011 Oct
2,mt001003,"GSM675524,GSM675525","SRX043468, SRX043469","SRR101406,SRR101407",GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,"Glucose_34C_rep1,Glucose_45C_rep2",wt,Glucose,34°,,2011 Oct
3,mt001004,GSM675521,SRX043465,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Glucose_45C_rep1,wt,Glucose,45°,,2011 Oct
4,mt001005,GSM675522,SRX043466,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Alfalfa_45C_rep1,wt,Alfalfa,45°,,2011 Oct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,mt014008,"GSM6873690,GSM6873691","SRX18797663, SRX18797664","SRR22838477,SRR22838476",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"MtLat-1_arabinan_4d_1,MtLat-1_arabinan_4d_2",MtLat-1,Arabinan,45°,4d,2023 Mar
104,mt014009,"GSM6873692,GSM6873693","SRX18797665, SRX18797666","SRR22838475,SRR22838474",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"MtAra-1_arabinose_4h_1,MtAra-1_arabinose_4h_2",MtAra,Aarabinose,45°,4h,2023 Mar
105,mt014010,"GSM6873694,GSM6873695","SRX18797667, SRX18797668","SRR22838473,SRR22838472",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"MtAra-1_xylose_4h_1,MtAra-1_xylose_4h_2",MtAra,Xylose,45°,4h,2023 Mar
106,mt014011,"GSM6873696,GSM6873697","SRX18797669, SRX18797670","SRR22838471,SRR22838470",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"MtAra-1_arabinan_4h_1,MtAra-1_arabinan_4h_2",MtAra,Arabinan,45°,4h,2023 Mar
107,mt014012,"GSM6873698,GSM6873699","SRX18797671, SRX18797672","SRR22838469,SRR22838468",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"WT_arabinan_4h_1,WT_arabinan_4h_2",wt,Arabinan,45°,4h,2023 Mar

In [5]:
# 保存
df_sample_change.to_csv('sample.tsv', sep='\t', index=False)