### 解析GSM.soft文件

In [10]:
import re
import os
import pandas as pd

def extract_information(file_path, df):
    """
    从GSM文件中提取特定信息，并将其存储在 DataFrame 中。
    """

    with open(file_path) as file:
        content = file.read()

    sample_accession = r'!Sample_geo_accession = (\w+)'
    try:
        sample = re.findall(sample_accession, content)
    except:
        sample = 'N/A'  

    organism = r'!Sample_organism_ch1 = (.*)'
    try:
        species = re.findall(organism, content)[0]
    except:
        species = 'N/A'

    strain_name = r'!Sample_characteristics_ch1 = (.*)'
    try:
        strain = re.findall(strain_name, content)[0]
    except: 
        strain = 'N/A'

    condition = r'!Sample_characteristics_ch1 = (.*)'
    try:
        condition = re.findall(condition, content)[1]
    except: 
        condition = 'N/A'

    condition_2 = r'!Sample_characteristics_ch1 = (.*)'
    try:
        condition_2 = re.findall(condition_2, content)[2]
    except: 
        condition_2 = 'N/A'
    
    condition_3 = r'!Sample_characteristics_ch1 = (.*)'
    try:
        condition_3 = re.findall(condition_2, content)[3]
    except: 
        condition_3 = 'N/A'

    taxid_id = r'!Sample_taxid_ch1 = (.*)'
    try:
        taxid = re.findall(taxid_id, content)[0]
    except:
        taxid = 'N/A'

    # protocol_txt = r'Sample_growth_protocol_ch1 = (.*)'
    # try:
    #     proticol = re.findall(protocol_txt, content)[0]
    # except: 
    #     proticol = 'N/A'

    model_id = r'Sample_instrument_model = (.*)'
    try:
        model = re.findall(model_id,content)
    except:
        model = 'N/A'

    selection_id = r'!Sample_library_selection = (.*)'
    try:
        library_selection = re.findall(selection_id,content)
    except:
        library_selection = 'N/A'

    source_id = r'!Sample_library_source = (.*)'
    try:
        library_source = re.findall(source_id,content)
    except:
        library_source = 'N/A'

    strategy_id = r'!Sample_library_strategy = (.*)'
    try:
        library_strategy = re.findall(strategy_id,content)
    except:
        library_strategy = 'N/A'

    spx_id = r'!Sample_relation = SRA:(.*)'
    try:
        experiment = re.findall(spx_id, content)
    except:
        experiment = 'N/A'

    series_id = r'!Sample_series_id = (.*)'
    try:
        series = re.findall(series_id,content)[0]
    except:
        series = 'N/A'


    # df_temp = pd.DataFrame(columns=['Sample','Species','Strain','TAXID','Protocol','Model','Library_seletion','Library_source','Library_strategy','Series','Condition','Condition_2','Condition_3'])
    df_temp = pd.DataFrame(columns=['Sample','Species','Strain','TAXID','Model','Library_seletion','Library_source','Library_strategy','Experiment','Series','Condition','Condition_2','Condition_3'])
    
    df_temp['Sample'] = sample
    df_temp['Species'] = species
    df_temp['Strain'] = strain
    df_temp['TAXID'] = taxid
    # df_temp['Protocol'] = proticol
    df_temp['Model'] = model
    df_temp['Library_seletion'] = library_selection
    df_temp['Library_source'] = library_source
    df_temp['Library_strategy'] = library_strategy
    df_temp['Experiment'] = experiment
    df_temp['Series'] = series
    df_temp['Condition'] = condition
    df_temp['Condition_2'] = condition_2
    df_temp['Condition_3'] = condition_3

    df = pd.concat([df, df_temp], ignore_index=True)

    return df

In [11]:
"""
测试单个样本
"""

path = './Mt/GSM_soft/GSE110062_GSM.soft'
df = pd.DataFrame(columns=['Sample','Species','Strain','TAXID','Model','Library_seletion','Library_source','Library_strategy','Experiment','Series','Condition','Condition_2','Condition_3'])

extract_information(path,df)
# demo.to_excel('demo.xlsx',index=False)

,Sample,Species,Strain,TAXID,Model,Library_seletion,Library_source,Library_strategy,Experiment,Series,Condition,Condition_2,Condition_3
0,GSM2977199,Thermothelomyces thermophilus,strain: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX3643305,GSE110062,strain: ATCC 42464,strain: ATCC 42464,strain: ATCC 42464
1,GSM2977200,Thermothelomyces thermophilus,strain: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX3643306,GSE110062,strain: ATCC 42464,strain: ATCC 42464,strain: ATCC 42464
2,GSM2977201,Thermothelomyces thermophilus,strain: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX3643307,GSE110062,strain: ATCC 42464,strain: ATCC 42464,strain: ATCC 42464
3,GSM2977202,Thermothelomyces thermophilus,strain: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX3643308,GSE110062,strain: ATCC 42464,strain: ATCC 42464,strain: ATCC 42464
4,GSM2977203,Thermothelomyces thermophilus,strain: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX3643309,GSE110062,strain: ATCC 42464,strain: ATCC 42464,strain: ATCC 42464
5,GSM2977204,Thermothelomyces thermophilus,strain: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX3643310,GSE110062,strain: ATCC 42464,strain: ATCC 42464,strain: ATCC 42464

In [12]:
"""
批量处理
"""

path = './Mt/GSM_soft/'
key_name ='Mt'

# df = pd.DataFrame(columns=['Sample','Species','Strain','TAXID','Protocol','Model','Library_seletion','Library_source','Library_strategy','Series','Condition','Condition_2','Condition_3'])
df = pd.DataFrame(columns=['Sample','Strain','TAXID','Model','Library_seletion','Library_source','Library_strategy','Experiment','Series','Condition','Condition_2','Condition_3'])

for file in os.listdir(path):
    try:
        file_path = os.path.join(path, file)
        df = extract_information(file_path, df)
    except Exception as e:
        print(f"An error occurred while processing file:\n{file_path}\nError message: {str(e)}")

df

,Sample,Strain,TAXID,Model,Library_seletion,Library_source,Library_strategy,Experiment,Series,Condition,Condition_2,Condition_3,Species
0,GSM6206886,source: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1550...,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,Thermothelomyces thermophilus
1,GSM6206887,source: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1550...,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,Thermothelomyces thermophilus
2,GSM6206888,source: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1550...,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,Thermothelomyces thermophilus
3,GSM6206889,source: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1550...,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,Thermothelomyces thermophilus
4,GSM6206890,source: ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1550...,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,Thermothelomyces thermophilus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,GSM5577208,strain: ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1217...,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,Thermothelomyces thermophilus ATCC 42464
230,GSM5577209,strain: ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1217...,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,Thermothelomyces thermophilus ATCC 42464
231,GSM5577210,strain: ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1217...,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,Thermothelomyces thermophilus ATCC 42464
232,GSM5577211,strain: ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1217...,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,Thermothelomyces thermophilus ATCC 42464
233,GSM5577212,strain: ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,https://www.ncbi.nlm.nih.gov/sra?term=SRX1217...,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,Thermothelomyces thermophilus ATCC 42464

In [13]:
# df新建列，名为Fname,Run,Study Title,Sample Name,值为空
df['Sample ID'] = ''
df['Run'] = ''
df['Study Title'] = ''
df['Samples'] = ''
df['Treatment'] = ''
df['Year'] = ''
df['Species'] = ''

df.rename(columns={'Sample':'Sample Name'}, inplace=True)
df.rename(columns={'Series':'Series Accession'}, inplace=True)
df.rename(columns={'Library_seletion':'Library Seletion'}, inplace=True)
df.rename(columns={'Library_strategy':'Library Strategy'}, inplace=True)
df.rename(columns={'Library_source':'Library Source'}, inplace=True)

df['Experiment'] = df['Experiment'].str.replace('https://www.ncbi.nlm.nih.gov/sra?term=', '')

# Strain列中将source:改为空,strain:改为空,carbon source:改为空,tissue:改为空
df['Strain'] = df['Strain'].str.replace('source:', '')
df['Strain'] = df['Strain'].str.replace('strain:', '')
df['Strain'] = df['Strain'].str.replace('carbon source:', '')
df['Strain'] = df['Strain'].str.replace('tissue:', '')

df

,Sample Name,Strain,TAXID,Model,Library Seletion,Library Source,Library Strategy,Experiment,Series Accession,Condition,Condition_2,Condition_3,Species,Sample ID,Run,Study Title,Samples,Treatment,Year
0,GSM6206886,ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX15507624,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,,,,,,,
1,GSM6206887,ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX15507625,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,,,,,,,
2,GSM6206888,ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX15507626,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,,,,,,,
3,GSM6206889,ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX15507627,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,,,,,,,
4,GSM6206890,ATCC 42464,78579,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX15507628,GSE205182,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,GSM5577208,ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX12177105,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,,,,,,,
230,GSM5577209,ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX12177106,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,,,,,,,
231,GSM5577210,ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX12177107,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,,,,,,,
232,GSM5577211,ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX12177108,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,,,,,,,
233,GSM5577212,ATCC 42464,573729,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,SRX12177109,GSE184074,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,,,,,,,

In [14]:
# df重新排序
df = df[['Sample ID',
         'Sample Name',
         'Experiment',
         'Run',
         'Series Accession',
         'Study Title',
         'Species',
         'Strain',
         'Model',
         'Library Seletion',
         'Library Source',
         'Library Strategy',
         'Samples',
         'Treatment',
         'Condition',
         'Condition_2',
         'Condition_3',
         'Year']]

df.head()

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Strain,Model,Library Seletion,Library Source,Library Strategy,Samples,Treatment,Condition,Condition_2,Condition_3,Year
0,,GSM6206886,SRX15507624,,GSE205182,,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
1,,GSM6206887,SRX15507625,,GSE205182,,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
2,,GSM6206888,SRX15507626,,GSE205182,,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
3,,GSM6206889,SRX15507627,,GSE205182,,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
4,,GSM6206890,SRX15507628,,GSE205182,,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,

In [15]:
# 读取Mt.gse_info.xlsx文件
df_gse_info = pd.read_excel('Mt_gse_info.xlsx')

# 添加Study Title的内容
for i in range(len(df)):
    for j in range(len(df_gse_info)):
        if df.loc[i, 'Series Accession'] == df_gse_info.loc[j, 'GSE Series']:
            df.loc[i, 'Study Title'] = df_gse_info.loc[j, 'Title']

df

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Strain,Model,Library Seletion,Library Source,Library Strategy,Samples,Treatment,Condition,Condition_2,Condition_3,Year
0,,GSM6206886,SRX15507624,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
1,,GSM6206887,SRX15507625,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
2,,GSM6206888,SRX15507626,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
3,,GSM6206889,SRX15507627,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
4,,GSM6206890,SRX15507628,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,,GSM5577208,SRX12177105,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,
230,,GSM5577209,SRX12177106,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,
231,,GSM5577210,SRX12177107,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,
232,,GSM5577211,SRX12177108,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,
233,,GSM5577212,SRX12177109,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,

In [16]:
df_name = pd.read_excel('Mt_gsm_id.xlsx')

# 添加Sample Name的内容
for i in range(len(df)):
    for j in range(len(df_name)):
        if df.loc[i, 'Sample Name'] == df_name.loc[j, 'Accession']:
            df.loc[i, 'Samples'] = df_name.loc[j, 'Title']

df

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Strain,Model,Library Seletion,Library Source,Library Strategy,Samples,Treatment,Condition,Condition_2,Condition_3,Year
0,,GSM6206886,SRX15507624,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A4h_1,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
1,,GSM6206887,SRX15507625,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A4h_2,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
2,,GSM6206888,SRX15507626,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A4h_3,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
3,,GSM6206889,SRX15507627,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A6h_1,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
4,,GSM6206890,SRX15507628,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A6h_2,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,,GSM5577208,SRX12177105,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T45_2,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,
230,,GSM5577209,SRX12177106,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T45_3,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,
231,,GSM5577210,SRX12177107,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T50_1,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,
232,,GSM5577211,SRX12177108,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T50_2,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,
233,,GSM5577212,SRX12177109,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T50_3,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,

In [17]:
df_dataset = pd.read_excel('dataset.xlsx')

df_dataset

,Series Accession,Samples,Title,Abstract,Country,Institute,Journal,Year,PMID
0,GSE213576,36,The putative methyltransferase LaeA regulates ...,Filamentous fungi with the ability to use com...,NaN,NaN,Biotechnology for biofuels and bioproducts,2023 Apr,37013645.0
1,GSE213575,4,The putative methyltransferase LaeA regulates ...,Filamentous fungi with the ability to use com...,NaN,NaN,Biotechnology for biofuels and bioproducts,2023 Apr,37013645.0
2,GSE213573,8,The putative methyltransferase LaeA regulates ...,Filamentous fungi with the ability to use com...,NaN,NaN,Biotechnology for biofuels and bioproducts,2023 Apr,37013645.0
3,GSE213570,24,The putative methyltransferase LaeA regulates ...,Filamentous fungi with the ability to use com...,China,"Tianjin institute of industrial biotechnology,...",Biotechnology for biofuels and bioproducts,2023 Apr,37013645.0
4,GSE221464,24,The arabinose transporter MtLat-1 is involved ...,Filamentous fungi possess an array of secrete...,China,"Tianjin institute of industrial biotechnology,...",Biotechnology for biofuels and bioproducts,2023 Mar,36966330.0
5,GSE214002,8,The Weimberg pathway: an alternative for Mycel...,With D-xylose being the second most abundant ...,China,"Tianjin Institute of Industrial Biotechnology,...",Biotechnology for biofuels and bioproducts,2023 Jan,36691040.0
6,GSE214142,18,PFK2/FBPase-2 is a potential target for metabo...,The key enzyme 6-phosphofructo-2-kinase (PFK2)...,China,Chinese Academy of Sciences,Frontiers in microbiology,2022,36478865.0
7,GSE205182,18,"MtTRC-1, a Novel Transcription Factor, Regulat...",The thermophilic fungus Myceliophthora thermop...,China,TIB CAS,Applied and environmental microbiology,2022 Oct,36165620.0
8,GSE184074,12,Reconstruction and analysis of genome-scale me...,"Myceliophthora thermophila, a thermophilic fun...",China,"Tianjin Institute of Industrial Biotechnology,...",Biotechnology and bioengineering,2022 Jul,35257374.0
9,GSE183387,49,NaN,NaN,Germany,Technische Universität Berlin,NaN,NaN,NaN
10,GSE114057,15,Direct production of commodity chemicals from ...,The production of fuels and chemicals from ren...,China,"Tianjin institute of industrial biotechnology,...",Metabolic engineering,2020 Sep,31078793.0
11,GSE111986,6,"CLR-4, a novel conserved transcription factor ...",Fungal degradation of lignocellulosic biomass ...,China,"Tianjin institute of industrial biotechnology,...",Molecular microbiology,2019 Feb,30474279.0
12,GSE165516,12,Transcriptional Profiling of Myceliophthora th...,Efficient biological conversion of all sugars ...,China,"Tianjin institute of industrial biotechnology,...",Frontiers in microbiology,2021,33995328.0
13,GSE110062,6,Transcriptional analysis of Myceliophthora the...,Thermophilic fungus Myceliophthora thermophila...,China,"Tianjin institute of industrial biotechnology,...",Bioresource technology,2018 Oct,29843921.0
14,GSE137286,20,Myceliophthora thermophila Xyr1 is predominant...,Myceliophthora thermophila is a thermophilic ...,Netherlands,Centre of fungal biodiversity,Biotechnology for biofuels,2019,31534479.0
15,GSE57235,4,Transcriptome and exoproteome analysis of util...,Myceliophthora thermophila is a thermophilic f...,Canada,Concordia University,Fungal genetics and biology : FG & B,2014 Nov,24881579.0
16,GSE27323,18,Comparative genomic analysis of the thermophil...,Thermostable enzymes and thermophilic cell fac...,Canada,Concordia University,Nature biotechnology,2011 Oct,21964414.0

In [20]:
for i in range(len(df)):
    for j in range(len(df_dataset)):
        if df['Series Accession'][i] == df_dataset['Series Accession'][j]:
            df.loc[i, 'Year'] = df_dataset.loc[j, 'Year']

# df = df.sort_values(by='Year', ascending=False)
df

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Strain,Model,Library Seletion,Library Source,Library Strategy,Samples,Treatment,Condition,Condition_2,Condition_3,Year
0,,GSM6206886,SRX15507624,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A4h_1,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,2022 Oct
1,,GSM6206887,SRX15507625,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A4h_2,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,2022 Oct
2,,GSM6206888,SRX15507626,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A4h_3,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,2022 Oct
3,,GSM6206889,SRX15507627,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A6h_1,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,2022 Oct
4,,GSM6206890,SRX15507628,,GSE205182,"MtTRC-1, a Novel Transcription Factor, Regulat...",,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Mycth_90344_A6h_2,,cell type: mycelia cells,source: ATCC 42464,source: ATCC 42464,2022 Oct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,,GSM5577208,SRX12177105,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T45_2,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,2022 Jul
230,,GSM5577209,SRX12177106,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T45_3,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,2022 Jul
231,,GSM5577210,SRX12177107,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T50_1,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,2022 Jul
232,,GSM5577211,SRX12177108,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T50_2,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,2022 Jul
233,,GSM5577212,SRX12177109,,GSE184074,Reconstruction and analysis genome-scale metab...,,ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,T50_3,,temperature: 35° C,strain: ATCC 42464,strain: ATCC 42464,2022 Jul

In [21]:
df.to_excel('sample.xlsx', index=False)