In [4]:
import pandas  as pd

# mtd/search/myceliophthora_thermophila/genome/gene_information.csv
df = pd.read_csv('gene_information.csv')
df

,Gene,Chr,Start,End,Strand,Length,NCBI_gene_id,Protein_id,Uniport_id,Symbol,...,GO_type,KEGG_definition,KEGG,Knum,EC_number,Description,Pfam,Cazy,Nucleic_acid_sequence,Amino_acid_sequence
0,MYCTH_100011,NC_016472.1,6881744.0,6884436.0,-,2693.0,11505753.0,XP_003660026,G2Q701,NaN,...,NaN,NaN,NaN,NaN,NaN,2OG-Fe(II) oxygenase superfamily,2OG-FeII_Oxy_2,NaN,ATGAGTAACATCACCAACAAAGTGATTTCCCAGACGCTGTCCCCCG...,MSNITNKVISQTLSPVDVPPKTFTSSDTTKSRLAAQRLRIATKRAA...
1,MYCTH_100068,NC_016473.1,5265193.0,5266157.0,-,965.0,11512455.0,XP_003662402,G2Q913,NaN,...,"CC,BP,MF,MF,MF,BP,BP,CC,MF",NaN,NaN,K01181,3.2.1.8,Belongs to the glycosyl hydrolase 11 (cellulas...,"CBM_1,Glyco_hydro_11",GH11: Glycoside Hydrolases (GHs) CBM1: Carbohy...,ATGGTTGCTCTCTCTTCTCTCCTCGTCGCTGCCTCTGCGGCGGCCG...,MVALSSLLVAASAAAVAVAAPSEALQKRQTLTSSQTGFHDGFYYSF...
2,MYCTH_100089,NC_016473.1,5175196.0,5176687.0,+,1492.0,11512426.0,XP_003662373,G2Q8Y3,NaN,...,"MF,MF,BP",NaN,NaN,NaN,NaN,"protocatechuate 3,4-dioxygenase activity",Dioxygenase_C,NaN,ATGACGCTCAAGCAGTTGCTCATGAGCGCGCTGCTCGCAGCACCCG...,MTLKQLLMSALLAAPALAHPAHKEKVYAHAALPLERKSLAHCAAKF...
3,MYCTH_100127,NC_016473.1,5035300.0,5035892.0,+,593.0,11512377.0,XP_003662324,G2Q8N0,NaN,...,NaN,NaN,NaN,K09780,NaN,YCII-related domain,YCII,NaN,ATGGCGACAGAAGCGCCCAAGAAGATGGAATGGCTCGTGGTCGTTC...,MATEAPKKMEWLVVVPDFPGAHEKRIAVRPQHFANLGPVKESGVFQ...
4,MYCTH_100290,NC_016473.1,4391122.0,4393687.0,+,2566.0,11512195.0,XP_003662142,G2Q7I4,NaN,...,"CC,BP",NaN,NaN,K11501,NaN,Mis6,CENP-I,NaN,ATGCCGTCCCCAGAGGATGATGACCTTGGCGGTCTCATCGGAGATC...,MPSPEDDDLGGLIGDLEAASKVPAKRRQTNIKSTVEKATALLYDRG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9287,MYCTH_t95,NC_016474.1,1785962.0,1786056.0,-,95.0,11507534.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9288,MYCTH_t96,NC_016474.1,1472358.0,1472429.0,-,72.0,11507441.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9289,MYCTH_t97,NC_016474.1,942762.0,942861.0,-,100.0,11512736.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9290,MYCTH_t98,NC_016474.1,86102.0,86183.0,-,82.0,11512532.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9291,MYCTH_t99,NC_016475.1,66526.0,66615.0,+,90.0,11509875.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# 取Gene、Description、Symbol、EC_number
df_fifter = df[['Gene', 'Description', 'Symbol', 'EC_number']]
df_fifter

,Gene,Description,Symbol,EC_number
0,MYCTH_100011,2OG-Fe(II) oxygenase superfamily,NaN,NaN
1,MYCTH_100068,Belongs to the glycosyl hydrolase 11 (cellulas...,NaN,3.2.1.8
2,MYCTH_100089,"protocatechuate 3,4-dioxygenase activity",NaN,NaN
3,MYCTH_100127,YCII-related domain,NaN,NaN
4,MYCTH_100290,Mis6,NaN,NaN
...,...,...,...,...
9287,MYCTH_t95,NaN,NaN,NaN
9288,MYCTH_t96,NaN,NaN,NaN
9289,MYCTH_t97,NaN,NaN,NaN
9290,MYCTH_t98,NaN,NaN,NaN
9291,MYCTH_t99,NaN,NaN,NaN

In [6]:
# 保存df_fifter
df_fifter.to_csv('Gene_Descripition_Symbol_EC.csv', index=False)