In [2]:
import pandas as pd


# df_sample = pd.read_csv('sample.tsv', sep='\t')
df_sample = pd.read_excel('sample_师哥核定.xlsx')

# 将Time列的NaN值填充为空字符串
df_sample['Time'] = df_sample['Time'].fillna('')

df_sample

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Model,Library Seletion,Library Source,Library Strategy,Samples,Strain,Carbon Sources,Temperature,Time,Year
0,mt001001,GSM675519,SRX043463,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Barley_34C_rep1,wt,Barley,34°,,2011 Oct
1,mt001002,GSM675520,SRX043464,SRR101402,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Barley_45C_rep1,wt,Barley,45°,,2011 Oct
2,mt001004,GSM675521,SRX043465,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Glucose_45C_rep1,wt,Glucose,45°,,2011 Oct
3,mt001005,GSM675522,SRX043466,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Alfalfa_45C_rep1,wt,Alfalfa,45°,,2011 Oct
4,mt001002,GSM675523,SRX043467,SRR101405,GSE27323,Transcriptomic response to substrate and tempe...,Thermothelomyces thermophilus,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Myceliophthora_thermophila_Barley_45C_rep2,wt,Barley,45°,,2011 Oct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,mt014010,GSM6873695,SRX18797668,SRR22838472,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,MtAra-1_xylose_4h_2,MtAra,Xylose,45°,4h,2023 Mar
217,mt014011,GSM6873696,SRX18797669,SRR22838471,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,MtAra-1_arabinan_4h_1,MtAra,Arabinan,45°,4h,2023 Mar
218,mt014011,GSM6873697,SRX18797670,SRR22838470,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,MtAra-1_arabinan_4h_2,MtAra,Arabinan,45°,4h,2023 Mar
219,mt014012,GSM6873698,SRX18797671,SRR22838469,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,WT_arabinan_4h_1,wt,Arabinan,45°,4h,2023 Mar
220,mt014012,GSM6873699,SRX18797672,SRR22838468,GSE221464,The arabinose transporter MtLat-1 is involved ...,Thermothelomyces thermophilus ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,WT_arabinan_4h_2,wt,Arabinan,45°,4h,2023 Mar

In [3]:
# 删除Samples这一列中的Myceliophthora_thermophila_
df_sample['Samples'] = df_sample['Samples'].str.replace('Myceliophthora_thermophila_', '')
df_sample['Samples'] = df_sample['Samples'].str.replace('Myceliphothora thermophila ', '')

# 将Species这一列Thermothelomyces thermophilus改为Myceliophthora thermophila
df_sample['Species'] = df_sample['Species'].str.replace('Thermothelomyces thermophilus', 'Myceliphothora thermophila')
df_sample['Time'] = df_sample['Time'].fillna('')

df_sample

# 保存为tsv文件
df_sample.to_csv('sample_未聚合.tsv', sep='\t', index=False)

In [4]:
df_sample_change = df_sample.groupby('Sample ID').agg({
    'Sample Name':lambda x: ','.join(x),
    'Experiment':lambda x: ','.join(x),
    'Run':lambda x: ','.join(x),
    'Series Accession':lambda x: ','.join(x),
    'Study Title':lambda x: ';'.join(x),
    'Species':lambda x: ','.join(x),
    'Model':lambda x: ','.join(x),
    'Library Seletion':lambda x: ','.join(x),
    'Library Source':lambda x: ','.join(x),
    'Library Strategy':lambda x: ','.join(x),
    'Samples':lambda x: ','.join(x),
    'Strain':lambda x: ','.join(x),
    'Carbon Sources':lambda x: ','.join(x),
    'Temperature':lambda x: ','.join(x),
    'Time':lambda x: ','.join(x),
    'Year':lambda x: ','.join(x),
    }).reset_index()

# 显示处理后的结果
df_sample_change

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Model,Library Seletion,Library Source,Library Strategy,Samples,Strain,Carbon Sources,Temperature,Time,Year
0,mt001001,GSM675519,SRX043463,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Barley_34C_rep1,wt,Barley,34°,,2011 Oct
1,mt001002,"GSM675520,GSM675523","SRX043464, SRX043467","SRR101402,SRR101405","GSE27323,GSE27323",Transcriptomic response to substrate and tempe...,"Myceliphothora thermophila,Myceliphothora ther...","Illumina Genome Analyzer II,Illumina Genome An...","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","Barley_45C_rep1,Barley_45C_rep2","wt,wt","Barley,Barley","45°,45°",",","2011 Oct,2011 Oct"
2,mt001003,"GSM675524,GSM675525","SRX043468, SRX043469","SRR101406,SRR101407","GSE27323,GSE27323",Transcriptomic response to substrate and tempe...,"Myceliphothora thermophila,Myceliphothora ther...","Illumina Genome Analyzer II,Illumina Genome An...","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","Glucose_34C_rep1,Glucose_45C_rep2","wt,wt","Glucose,Glucose","34°,45°",",","2011 Oct,2011 Oct"
3,mt001004,GSM675521,SRX043465,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Glucose_45C_rep1,wt,Glucose,45°,,2011 Oct
4,mt001005,GSM675522,SRX043466,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Alfalfa_45C_rep1,wt,Alfalfa,45°,,2011 Oct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,mt014008,"GSM6873690,GSM6873691","SRX18797663, SRX18797664","SRR22838477,SRR22838476","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","MtLat-1_arabinan_4d_1,MtLat-1_arabinan_4d_2","MtLat-1,MtLat-1","Arabinan,Arabinan","45°,45°","4d,4d","2023 Mar,2023 Mar"
104,mt014009,"GSM6873692,GSM6873693","SRX18797665, SRX18797666","SRR22838475,SRR22838474","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","MtAra-1_arabinose_4h_1,MtAra-1_arabinose_4h_2","MtAra,MtAra","Aarabinose,Aarabinose","45°,45°","4h,4h","2023 Mar,2023 Mar"
105,mt014010,"GSM6873694,GSM6873695","SRX18797667, SRX18797668","SRR22838473,SRR22838472","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","MtAra-1_xylose_4h_1,MtAra-1_xylose_4h_2","MtAra,MtAra","Xylose,Xylose","45°,45°","4h,4h","2023 Mar,2023 Mar"
106,mt014011,"GSM6873696,GSM6873697","SRX18797669, SRX18797670","SRR22838471,SRR22838470","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","MtAra-1_arabinan_4h_1,MtAra-1_arabinan_4h_2","MtAra,MtAra","Arabinan,Arabinan","45°,45°","4h,4h","2023 Mar,2023 Mar"
107,mt014012,"GSM6873698,GSM6873699","SRX18797671, SRX18797672","SRR22838469,SRR22838468","GSE221464,GSE221464",The arabinose transporter MtLat-1 is involved ...,"Myceliphothora thermophila ATCC 42464,Myceliph...","Illumina HiSeq 2000,Illumina HiSeq 2000","cDNA,cDNA","transcriptomic,transcriptomic","RNA-Seq,RNA-Seq","WT_arabinan_4h_1,WT_arabinan_4h_2","wt,wt","Arabinan,Arabinan","45°,45°","4h,4h","2023 Mar,2023 Mar"

In [5]:
# Series ID这一列中，存在多个值，如果值相同则值合并
df_sample_change['Series Accession'] = df_sample_change['Series Accession'].str.split(',').str[0]
df_sample_change['Study Title'] = df_sample_change['Study Title'].str.split(';').str[0]
df_sample_change['Species'] = df_sample_change['Species'].str.split(',').str[0]
df_sample_change['Strain'] = df_sample_change['Strain'].str.split(',').str[0]
df_sample_change['Model'] = df_sample_change['Model'].str.split(',').str[0]
df_sample_change['Library Seletion'] = df_sample_change['Library Seletion'].str.split(',').str[0]
df_sample_change['Library Source'] = df_sample_change['Library Source'].str.split(',').str[0]
df_sample_change['Library Strategy'] = df_sample_change['Library Strategy'].str.split(',').str[0]
df_sample_change['Strain'] = df_sample_change['Strain'].str.split(',').str[0]
df_sample_change['Carbon Sources'] = df_sample_change['Carbon Sources'].str.split(',').str[0]
df_sample_change['Temperature'] = df_sample_change['Temperature'].str.split(',').str[0]
df_sample_change['Time'] = df_sample_change['Time'].str.split(',').str[0]
df_sample_change['Year'] = df_sample_change['Year'].str.split(',').str[0]

df_sample_change

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Model,Library Seletion,Library Source,Library Strategy,Samples,Strain,Carbon Sources,Temperature,Time,Year
0,mt001001,GSM675519,SRX043463,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Barley_34C_rep1,wt,Barley,34°,,2011 Oct
1,mt001002,"GSM675520,GSM675523","SRX043464, SRX043467","SRR101402,SRR101405",GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,"Barley_45C_rep1,Barley_45C_rep2",wt,Barley,45°,,2011 Oct
2,mt001003,"GSM675524,GSM675525","SRX043468, SRX043469","SRR101406,SRR101407",GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,"Glucose_34C_rep1,Glucose_45C_rep2",wt,Glucose,34°,,2011 Oct
3,mt001004,GSM675521,SRX043465,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Glucose_45C_rep1,wt,Glucose,45°,,2011 Oct
4,mt001005,GSM675522,SRX043466,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Alfalfa_45C_rep1,wt,Alfalfa,45°,,2011 Oct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,mt014008,"GSM6873690,GSM6873691","SRX18797663, SRX18797664","SRR22838477,SRR22838476",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"MtLat-1_arabinan_4d_1,MtLat-1_arabinan_4d_2",MtLat-1,Arabinan,45°,4d,2023 Mar
104,mt014009,"GSM6873692,GSM6873693","SRX18797665, SRX18797666","SRR22838475,SRR22838474",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"MtAra-1_arabinose_4h_1,MtAra-1_arabinose_4h_2",MtAra,Aarabinose,45°,4h,2023 Mar
105,mt014010,"GSM6873694,GSM6873695","SRX18797667, SRX18797668","SRR22838473,SRR22838472",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"MtAra-1_xylose_4h_1,MtAra-1_xylose_4h_2",MtAra,Xylose,45°,4h,2023 Mar
106,mt014011,"GSM6873696,GSM6873697","SRX18797669, SRX18797670","SRR22838471,SRR22838470",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"MtAra-1_arabinan_4h_1,MtAra-1_arabinan_4h_2",MtAra,Arabinan,45°,4h,2023 Mar
107,mt014012,"GSM6873698,GSM6873699","SRX18797671, SRX18797672","SRR22838469,SRR22838468",GSE221464,The arabinose transporter MtLat-1 is involved ...,Myceliphothora thermophila ATCC 42464,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,"WT_arabinan_4h_1,WT_arabinan_4h_2",wt,Arabinan,45°,4h,2023 Mar

In [6]:
# 创建df_sample_filter，取Sample ID、Sample Name、Study Title、Strain、Carbon Sources、Temperature、Time这几列
df_sample_filter = df_sample_change[['Sample ID', 'Strain', 'Carbon Sources', 'Temperature', 'Time', 'Study Title', 'Series Accession', 'Sample Name']].copy()

# 将列名Sample Name改为Related Sample
df_sample_filter.rename(columns={'Sample Name':'Related Sample'}, inplace=True)

df_sample_filter

,Sample ID,Strain,Carbon Sources,Temperature,Time,Study Title,Series Accession,Related Sample
0,mt001001,wt,Barley,34°,,Transcriptomic response to substrate and tempe...,GSE27323,GSM675519
1,mt001002,wt,Barley,45°,,Transcriptomic response to substrate and tempe...,GSE27323,"GSM675520,GSM675523"
2,mt001003,wt,Glucose,34°,,Transcriptomic response to substrate and tempe...,GSE27323,"GSM675524,GSM675525"
3,mt001004,wt,Glucose,45°,,Transcriptomic response to substrate and tempe...,GSE27323,GSM675521
4,mt001005,wt,Alfalfa,45°,,Transcriptomic response to substrate and tempe...,GSE27323,GSM675522
...,...,...,...,...,...,...,...,...
103,mt014008,MtLat-1,Arabinan,45°,4d,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873690,GSM6873691"
104,mt014009,MtAra,Aarabinose,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873692,GSM6873693"
105,mt014010,MtAra,Xylose,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873694,GSM6873695"
106,mt014011,MtAra,Arabinan,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873696,GSM6873697"
107,mt014012,wt,Arabinan,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873698,GSM6873699"

In [7]:
# 读取mtd/search/myceliophthora_thermophila/transcriptome/backup_v2.0/dataset.xlsx
df_dataset = pd.read_excel('dataset.xlsx')

# 显示df_dataset
df_dataset

,Series Accession,Samples,Title,Abstract,Country,Institute,Journal,Year,PMID
0,GSE213575,4,The putative methyltransferase LaeA regulates ...,Filamentous fungi with the ability to use com...,China,"Tianjin institute of industrial biotechnology,...",Biotechnology for biofuels and bioproducts,2023 Apr,37013645.0
1,GSE213573,8,The putative methyltransferase LaeA regulates ...,Filamentous fungi with the ability to use com...,China,"Tianjin institute of industrial biotechnology,...",Biotechnology for biofuels and bioproducts,2023 Apr,37013645.0
2,GSE213570,24,The putative methyltransferase LaeA regulates ...,Filamentous fungi with the ability to use com...,China,"Tianjin institute of industrial biotechnology,...",Biotechnology for biofuels and bioproducts,2023 Apr,37013645.0
3,GSE221464,24,The arabinose transporter MtLat-1 is involved ...,Filamentous fungi possess an array of secrete...,China,"Tianjin institute of industrial biotechnology,...",Biotechnology for biofuels and bioproducts,2023 Mar,36966330.0
4,GSE214002,8,The Weimberg pathway: an alternative for Mycel...,With D-xylose being the second most abundant ...,China,"Tianjin Institute of Industrial Biotechnology,...",Biotechnology for biofuels and bioproducts,2023 Jan,36691040.0
5,GSE214142,18,PFK2/FBPase-2 is a potential target for metabo...,The key enzyme 6-phosphofructo-2-kinase (PFK2)...,China,"Tianjin institute of industrial biotechnology,...",Frontiers in microbiology,2022,36478865.0
6,GSE205182,18,"MtTRC-1, a Novel Transcription Factor, Regulat...",The thermophilic fungus Myceliophthora thermop...,China,"Tianjin Institute of Industrial Biotechnology,...",Applied and environmental microbiology,2022 Oct,36165620.0
7,GSE184074,12,Reconstruction and analysis of genome-scale me...,"Myceliophthora thermophila, a thermophilic fun...",China,"Tianjin Institute of Industrial Biotechnology,...",Biotechnology and bioengineering,2022 Jul,35257374.0
8,GSE183387,49,Transcriptomic insights into the roles of the ...,"Thermothelomyces thermophilus, formerly known ...",Germany,Technische Universität Berlin,NaN,2021 Sep,NaN
9,GSE114057,15,Direct production of commodity chemicals from ...,The production of fuels and chemicals from ren...,China,"Tianjin institute of industrial biotechnology,...",Metabolic engineering,2020 Sep,31078793.0
10,GSE111986,6,"CLR-4, a novel conserved transcription factor ...",Fungal degradation of lignocellulosic biomass ...,China,"Tianjin institute of industrial biotechnology,...",Molecular microbiology,2019 Feb,30474279.0
11,GSE165516,12,Transcriptional Profiling of Myceliophthora th...,Efficient biological conversion of all sugars ...,China,"Tianjin institute of industrial biotechnology,...",Frontiers in microbiology,2021,33995328.0
12,GSE110062,6,Transcriptional analysis of Myceliophthora the...,Thermophilic fungus Myceliophthora thermophila...,China,"Tianjin institute of industrial biotechnology,...",Bioresource technology,2018 Oct,29843921.0
13,GSE137286,20,Myceliophthora thermophila Xyr1 is predominant...,Myceliophthora thermophila is a thermophilic ...,Netherlands,Centre of fungal biodiversity,Biotechnology for biofuels,2019,31534479.0
14,GSE57235,4,Transcriptome and exoproteome analysis of util...,Myceliophthora thermophila is a thermophilic f...,Canada,Concordia University,Fungal genetics and biology : FG & B,2014 Nov,24881579.0
15,GSE27323,18,Comparative genomic analysis of the thermophil...,Thermostable enzymes and thermophilic cell fac...,Canada,Concordia University,Nature biotechnology,2011 Oct,21964414.0

In [8]:
# df _sample_filter新添加一列，列名为Title，值为df_dataset中Title列的值，根据Series Accession列进行匹配
df_sample_filter['Title'] = df_sample_filter['Series Accession'].map(df_dataset.set_index('Series Accession')['Title'])

# 显示df_sample_filter
df_sample_filter

,Sample ID,Strain,Carbon Sources,Temperature,Time,Study Title,Series Accession,Related Sample,Title
0,mt001001,wt,Barley,34°,,Transcriptomic response to substrate and tempe...,GSE27323,GSM675519,Comparative genomic analysis of the thermophil...
1,mt001002,wt,Barley,45°,,Transcriptomic response to substrate and tempe...,GSE27323,"GSM675520,GSM675523",Comparative genomic analysis of the thermophil...
2,mt001003,wt,Glucose,34°,,Transcriptomic response to substrate and tempe...,GSE27323,"GSM675524,GSM675525",Comparative genomic analysis of the thermophil...
3,mt001004,wt,Glucose,45°,,Transcriptomic response to substrate and tempe...,GSE27323,GSM675521,Comparative genomic analysis of the thermophil...
4,mt001005,wt,Alfalfa,45°,,Transcriptomic response to substrate and tempe...,GSE27323,GSM675522,Comparative genomic analysis of the thermophil...
...,...,...,...,...,...,...,...,...,...
103,mt014008,MtLat-1,Arabinan,45°,4d,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873690,GSM6873691",The arabinose transporter MtLat-1 is involved ...
104,mt014009,MtAra,Aarabinose,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873692,GSM6873693",The arabinose transporter MtLat-1 is involved ...
105,mt014010,MtAra,Xylose,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873694,GSM6873695",The arabinose transporter MtLat-1 is involved ...
106,mt014011,MtAra,Arabinan,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873696,GSM6873697",The arabinose transporter MtLat-1 is involved ...
107,mt014012,wt,Arabinan,45°,4h,The arabinose transporter MtLat-1 is involved ...,GSE221464,"GSM6873698,GSM6873699",The arabinose transporter MtLat-1 is involved ...

In [10]:
df = df_sample_filter[['Sample ID', 'Strain', 'Carbon Sources', 'Temperature', 'Time', 'Title', 'Series Accession', 'Related Sample']].copy()
df

# 保存为tsv文件
df.to_csv('sample.tsv', sep='\t', index=False)