In [27]:
import pandas as pd
import json

In [28]:
df = pd.read_excel('dataset.xlsx', sheet_name='Sheet1')
df

,GEO Series,Species,Samples,Title,Summary,Keyword,Publication,Journal,Institution,Country,Contributor
0,GSE183387,Thermothelomyces thermophilus,49,Transcriptomic insights into the roles of the ...,"Thermothelomyces thermophilus, formerly known ...",NaN,NaN,NaN,"Technische Universität Berlin, Benedikt Siebecker",Germany,Siebecker B
1,GSE137286,Thermothelomyces thermophilus,20,Myceliophthora thermophila Xyr1 is predominant...,The aim of this study is to investigate the ro...,"'Cellulose degradation', 'Myceliophthora therm...",31534479.0,Biotechnol Biofuels,"fungal physiology, Centre of fungal biodiversity",Netherlands,Ronald P de Vries
2,GSE184074,Thermothelomyces thermophilus,12,Reconstruction and analysis genome-scale metab...,Myceliophthora thermophila is a thermophilic f...,"'Myceliophthora thermophila', 'genome-scale me...",35257374.0,Biotechnol Bioeng,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian
3,GSE205182,Thermothelomyces thermophilus,18,"MtTRC-1, a Novel Transcription Factor, Regulat...","In thermophilic fungi, work on the ER stress a...","'ER stress', 'MtHAC-1', 'MtTRC-1', 'Mtcbh-1', ...",36165620.0,Appl Environ Microbiol,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian
4,GSE214002,Thermothelomyces thermophilus,8,Weimberg pathway an alternative for utilizatio...,"An alternative for utilization of D-xylose, th...","'1,2,4-Butanetriol', 'D-Xylose', 'D-Xylose deh...",36691040.0,Biotechnol Biofuels Bioprod,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian
5,GSE214142,Thermothelomyces thermophilus,18,PFK2/FBPase-2 is a potential target for metabo...,The PFK-2/ FBPase-2 are important regulatory e...,"'6-phosphofructo-2-kinase/fructose-2,6-biphosp...",36478865.0,Front Microbiol,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian
6,GSE110062,Thermothelomyces thermophilus,6,Transcriptional landscape of Myceliophthora th...,Thermophilic fungus Myceliophthora thermophila...,"'Cellulose', 'Myceliophthora thermophila', 'St...",29843921.0,Bioresour Technol,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian
7,GSE111986,Thermothelomyces thermophilus,4,A novel conserved transcription factor CLR-4 r...,Fungal degradation of lignocellulosic biomass ...,NaN,30474279.0,Mol Microbiol,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian
8,GSE114057,Thermothelomyces thermophilus,15,Engineering the Cellulolytic Fungus Myceliopht...,Producing the fuels and chemicals from renewab...,"'Biochemicals', 'C4-diacid', 'CRISPR/Cas9', 'C...",31078793.0,Metab Eng,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian
9,GSE165516,Thermothelomyces thermophilus,12,Transcriptional profiling of Myceliophthora th...,Transcriptional landscape of MyceliopTranscrip...,"'Myceliophthora', 'galactose transport', 'gala...",33995328.0,Front Microbiol,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian
10,GSE57235,Thermothelomyces thermophilus,4,Transcriptomic response to different biomass i...,The thermophilic filamentous fungi Myceliophth...,"'Biomass degradation', 'Carbohydrate-active en...",24881579.0,Fungal Genet Biol,"Centre for Structural and Functional Genomics,...",Canada,Adrian Tsang
11,GSE27323,Thermothelomyces thermophilus,7,Transcriptomic response to substrate and tempe...,The thermophilic filamentous fungi Myceliophth...,NaN,21964414.0,Nat Biotechnol,"Centre for Structural and Functional Genomics,...",Canada,Adrian Tsang
12,NaN,NaN,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# 新建一个df，列为df中的Institution，Country，Contributor，Samples列
df1 = df[['Institution', 'Country', 'Contributor', 'Samples']]
df1

,Institution,Country,Contributor,Samples
0,"Technische Universität Berlin, Benedikt Siebecker",Germany,Siebecker B,49
1,"fungal physiology, Centre of fungal biodiversity",Netherlands,Ronald P de Vries,20
2,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian,12
3,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian,18
4,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian,8
5,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian,18
6,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian,6
7,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian,4
8,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian,15
9,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian,12
10,"Centre for Structural and Functional Genomics,...",Canada,Adrian Tsang,4
11,"Centre for Structural and Functional Genomics,...",Canada,Adrian Tsang,7
12,NaN,NaN,NaN,93

In [30]:
# 将Contributor列中同样的作者合并，Samples列中的样本数相加
df2 = df1.groupby(['Institution', 'Country', 'Contributor']).sum()

# 将df2中的index转换为columns
df2 = df2.reset_index()

df2

,Institution,Country,Contributor,Samples
0,"Centre for Structural and Functional Genomics,...",Canada,Adrian Tsang,11
1,"Technische Universität Berlin, Benedikt Siebecker",Germany,Siebecker B,49
2,"Tianjin institute of industrial biotechnology,...",China,Chaoguang Tian,93
3,"fungal physiology, Centre of fungal biodiversity",Netherlands,Ronald P de Vries,20

In [31]:
# df2转为字典
df2_dict = df2.to_dict(orient='records')
df2_dict

[{'Institution': 'Centre for Structural and Functional Genomics, Biology, Concordia University,',
  'Country': 'Canada',
  'Contributor': 'Adrian Tsang',
  'Samples': 11},
 {'Institution': 'Technische Universität Berlin, Benedikt Siebecker',
  'Country': 'Germany',
  'Contributor': 'Siebecker B',
  'Samples': 49},
 {'Institution': 'Tianjin institute of industrial biotechnology,Chinses Academy of Sciences',
  'Country': 'China',
  'Contributor': 'Chaoguang Tian',
  'Samples': 93},
 {'Institution': 'fungal physiology, Centre of fungal biodiversity',
  'Country': 'Netherlands',
  'Contributor': 'Ronald P de Vries',
  'Samples': 20}]

In [32]:
output = {}

for item in df2_dict:
    if item['Country'] not in output:
        output[item['Country']] = {}
    if item['Contributor'] not in output[item['Country']]:
        output[item['Country']][item['Contributor']] = {}
        output[item['Country']][item['Contributor']]['Unit'] = item['Institution']
        output[item['Country']][item['Contributor']]['Samples'] = str(item['Samples'])

# 将output字典转换为json格式
output_json = json.dumps(output, ensure_ascii=False, indent=4)

# 将output_json写入文件
with open('map.json', 'w', encoding='utf-8') as f:
    f.write(output_json)